### ISSUE TITLE
Explanation on website

### ISSUE THREAD

**Issue by Steffen1996** [zaiste/vimified#131]
I dont know if i am on the right issue page, but its so tiny i dont think that it matters. On the website the step for creating tmp/ folders is missing. Took me nearly 10 minutes to resolve it, and i think we could save this few minutes for other people :)

**Comment by zaiste** [comment]
@Steffen1996 would you be willing to issue a pull request ?

**Comment by Steffen1996** [comment]
#132 :)

**Comment by Steffen1996** [comment]
Reopened until merge ...
